services:
    traefik:
        image: traefik:v3.0
        container_name: dolmebel-traefik
        restart: unless-stopped
        command:
            - --api.dashboard=true
            - --api.insecure=false
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
            - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@dolmebel.com}
            - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
            - --log.level=INFO
            - --accesslog=true
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"  # Traefik dashboard
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik-letsencrypt:/letsencrypt
        networks:
            - turahe
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.dolmebel.local`) || Host(`traefik.dolmebel.com`)
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.tls.certresolver=letsencrypt
            - traefik.http.services.traefik.loadbalancer.server.port=8080

    app:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: turahe/dolmebel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_turahe: 1
            XDEBUG_MODE: '${turahe_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${turahe_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - turahe
        depends_on:
            - pgsql
            - redis
            - meilisearch
            - minio
            - mailpit
            - rabbitmq
            - soketi
            - mysql
        labels:
            - traefik.enable=true
            - traefik.http.routers.app.rule=Host(`dolmebel.local`) || Host(`dolmebel.com`)
            - traefik.http.routers.app.entrypoints=websecure
            - traefik.http.routers.app.tls.certresolver=letsencrypt
            - traefik.http.services.app.loadbalancer.server.port=80
            - traefik.http.middlewares.app-headers.headers.customrequestheaders.X-Forwarded-Proto=https
            - traefik.http.routers.app.middlewares=app-headers
    pgsql:
        image: 'postgres:17-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'turahe-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'turahe-redis:/data'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'turahe-meilisearch:/meili_data'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: turahe
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'turahe-minio:/data'
        networks:
            - turahe
        command: 'minio server /data --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - mc
                - ready
                - local
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - turahe
        labels:
            - traefik.enable=true
            - traefik.http.routers.mailpit.rule=Host(`mailpit.${DOMAIN:-dolmebel.com}`)
            - traefik.http.routers.mailpit.entrypoints=websecure
            - traefik.http.routers.mailpit.tls.certresolver=letsencrypt
            - traefik.http.services.mailpit.loadbalancer.server.port=8025
    rabbitmq:
        image: 'rabbitmq:4-management-alpine'
        hostname: rabbitmq
        ports:
            - '${FORWARD_RABBITMQ_PORT:-5672}:5672'
            - '${FORWARD_RABBITMQ_DASHBOARD_PORT:-15672}:15672'
        environment:
            RABBITMQ_HOST: '%'
            RABBITMQ_USER: '${RABBITMQ_USER}'
            RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD}'
            RABBITMQ_VHOST: '${RABBITMQ_VHOST}'
            RABBITMQ_QUEUE: '${RABBITMQ_QUEUE}'
        volumes:
            - 'turahe-rabbitmq:/var/lib/rabbitmq'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - rabbitmq-diagnostics
                - '-q'
                - ping
            retries: 3
            timeout: 5s
        labels:
            - traefik.enable=true
            - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.${DOMAIN:-dolmebel.com}`)
            - traefik.http.routers.rabbitmq.entrypoints=websecure
            - traefik.http.routers.rabbitmq.tls.certresolver=letsencrypt
            - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - turahe
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'turahe-mysql:/var/lib/mysql'
            - './vendor/laravel/turahe/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    turahe:
        driver: bridge
volumes:
    turahe-pgsql:
        driver: local
    turahe-redis:
        driver: local
    turahe-meilisearch:
        driver: local
    turahe-minio:
        driver: local
    turahe-rabbitmq:
        driver: local
    turahe-mysql:
        driver: local
    traefik-letsencrypt:
        driver: local
