services:
    traefik:
        image: traefik:v3.0
        container_name: dolmebel-traefik
        restart: unless-stopped
        command:
            - --api.dashboard=true
            - --api.insecure=false
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
            - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@dolmebel.com}
            - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
            - --log.level=INFO
            - --accesslog=true
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"  # Traefik dashboard
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/traefik:/letsencrypt
        networks:
            - turahe
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.dolmebel.local`) || Host(`traefik.dolmebel.com`)
            - traefik.http.routers.traefik.entrypoints=${TRAEFIK_ENTRYPOINT:-web}
            - traefik.http.routers.traefik.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-}
            - traefik.http.services.traefik.loadbalancer.server.port=8080

    app:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: turahe/dolmebel
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        # Vite dev server accessible through Traefik
        # ports:
        #     - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_turahe: 1
            APP_ENV: '${APP_ENV:-local}'
            APP_DEBUG: '${APP_DEBUG:-true}'
            APP_URL: '${APP_URL:-http://dolmebel.local}'
            XDEBUG_MODE: '${turahe_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${turahe_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - turahe
        depends_on:
            - pgsql
            - redis
            - meilisearch
            - minio
            - mailpit
            - rabbitmq
            - soketi
        labels:
            - traefik.enable=true
            - traefik.http.routers.app.rule=Host(`dolmebel.local`) || Host(`dolmebel.com`)
            - traefik.http.routers.app.entrypoints=${TRAEFIK_ENTRYPOINT:-web}
            - traefik.http.routers.app.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-}
            - traefik.http.services.app.loadbalancer.server.port=80
            - traefik.http.middlewares.app-headers.headers.customrequestheaders.X-Forwarded-Proto=${TRAEFIK_PROTO:-http}
            - traefik.http.routers.app.middlewares=app-headers
    pgsql:
        image: 'postgres:17-alpine'
        container_name: dolmebel-postgres
        restart: unless-stopped
        # Database accessible through app container only
        # ports:
        #     - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './data/postgres:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: dolmebel-redis
        restart: unless-stopped
        # Redis accessible through app container only
        # ports:
        #     - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './data/redis:/data'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: dolmebel-meilisearch
        restart: unless-stopped
        # Meilisearch accessible through app container only
        # ports:
        #     - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: 'true'
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
        volumes:
            - './data/meilisearch:/meili_data'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        container_name: dolmebel-minio
        restart: unless-stopped
        # MinIO accessible through app container only
        # ports:
        #     - '${FORWARD_MINIO_PORT:-9000}:9000'
        #     - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
            MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
        volumes:
            - './data/minio:/data'
        networks:
            - turahe
        command: 'minio server /data --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - mc
                - ready
                - local
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: dolmebel-mailpit
        restart: unless-stopped
        # Mailpit accessible through app container only
        # ports:
        #     - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        #     - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - turahe
        labels:
            - traefik.enable=true
            - traefik.http.routers.mailpit.rule=Host(`mailpit.${DOMAIN:-dolmebel.com}`)
            - traefik.http.routers.mailpit.entrypoints=${TRAEFIK_ENTRYPOINT:-web}
            - traefik.http.routers.mailpit.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-}
            - traefik.http.services.mailpit.loadbalancer.server.port=8025
    rabbitmq:
        image: 'rabbitmq:4-management-alpine'
        container_name: dolmebel-rabbitmq
        hostname: rabbitmq
        restart: unless-stopped
        # RabbitMQ accessible through app container only
        # ports:
        #     - '${FORWARD_RABBITMQ_PORT:-5672}:5672'
        #     - '${FORWARD_RABBITMQ_DASHBOARD_PORT:-15672}:15672'
        environment:
            RABBITMQ_HOST: '%'
            RABBITMQ_USER: '${RABBITMQ_USER}'
            RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD}'
            RABBITMQ_VHOST: '${RABBITMQ_VHOST}'
            RABBITMQ_QUEUE: '${RABBITMQ_QUEUE}'
        volumes:
            - './data/rabbitmq:/var/lib/rabbitmq'
        networks:
            - turahe
        healthcheck:
            test:
                - CMD
                - rabbitmq-diagnostics
                - '-q'
                - ping
            retries: 3
            timeout: 5s
        labels:
            - traefik.enable=true
            - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.${DOMAIN:-dolmebel.com}`)
            - traefik.http.routers.rabbitmq.entrypoints=${TRAEFIK_ENTRYPOINT:-web}
            - traefik.http.routers.rabbitmq.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-}
            - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        container_name: dolmebel-soketi
        restart: unless-stopped
        environment:
            SOKETI_DEBUG: '0'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        # Soketi accessible through app container only
        # ports:
        #     - '${PUSHER_PORT:-6001}:6001'
        #     - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - turahe
networks:
    turahe:
        driver: bridge
